-- Update sightings with coordinates
-- Generated by LLM geocoding

-- Bear Creek Falls, Ouray
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-107.6705 37.9433)', 4326)
WHERE location_name = 'Bear Creek Falls, Ouray' AND location IS NULL;

-- Bear Peak
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.29 40.015)', 4326)
WHERE location_name = 'Bear Peak' AND location IS NULL;

-- Elk Falls
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.0833 37.8833)', 4326)
WHERE location_name = 'Elk Falls' AND location IS NULL;

-- Trail Ridge Road area
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.6836 40.3663)', 4326)
WHERE location_name LIKE '%Trail Ridge Road%' AND location IS NULL;

-- Staunton State Park
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.3085 39.4063)', 4326)
WHERE location_name = 'Staunton State Park' AND location IS NULL;

-- Quandary Peak
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-106.1005 39.3995)', 4326)
WHERE location_name = 'Quandary Peak' AND location IS NULL;

-- Yellow Jacket Mine, Bear Creek
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-107.6633 37.9333)', 4326)
WHERE location_name LIKE '%Yellow Jacket Mine%' AND location IS NULL;

-- Crestone area
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.585 37.999)', 4326)
WHERE location_name LIKE '%Crestone%' AND location IS NULL;

-- Rocky Mountain National Park general
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.6836 40.3428)', 4326)
WHERE (location_name LIKE '%RMNP%' OR location_name LIKE '%Rocky Mountain National Park%') 
AND location IS NULL;

-- Bear Lake specific
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.6824 40.3845)', 4326)
WHERE location_name LIKE '%Bear Lake%' 
AND location_name NOT LIKE '%Road%'
AND location_name NOT LIKE '%Corridor%'
AND location IS NULL;

-- Bear Lake Road/Corridor
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.5852 40.3845)', 4326)
WHERE (location_name LIKE '%Bear Lake Road%' OR location_name LIKE '%Bear Lake Corridor%')
AND location IS NULL;

-- Park County
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.5006 39.187)', 4326)
WHERE location_name = 'Park County' AND location IS NULL;

-- Moraine Park
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.5855 40.3664)', 4326)
WHERE location_name LIKE '%Moraine Park%' AND location IS NULL;

-- Estes Park
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.5253 40.3775)', 4326)
WHERE location_name LIKE '%Estes Park%' AND location IS NULL;

-- Deer Mountain Trailhead
UPDATE sightings 
SET location = ST_GeomFromText('POINT(-105.5253 40.3775)', 4326)
WHERE location_name LIKE '%Deer Mountain%' AND location IS NULL;

-- Count how many we updated
SELECT COUNT(*) as updated_count 
FROM sightings 
WHERE location IS NOT NULL 
AND created_at >= '2025-06-28';

-- Verify some results
SELECT location_name, 
       ST_Y(location::geometry) as latitude,
       ST_X(location::geometry) as longitude,
       location_confidence_radius
FROM sightings 
WHERE location IS NOT NULL 
AND created_at >= '2025-06-28'
LIMIT 10;